### ISSUE TITLE
React & Redux group project: Set up Kanban board

### ISSUE THREAD

**Issue by williamscch** [williamscch/space-travelers#21]
[Link to our Github Project](https://github.com/williamscch/space-travelers/projects/1)
Note: We are just 2 people on our team.

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @williamscch and @amklass11,

Good job so far!
✔️ Kanban board columns are complete
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Your total tasks should be 17, but you have 13, because you are missing the following tasks

  ![the-4](https://user-images.githubusercontent.com/36542986/185966783-35d15e04-e830-4987-a231-120dbbf4dfba.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by williamscch** [comment]
@TedLivist Where can I get those tasks?

**Comment by julie-ify** [comment]
@williamscch they are there on the template from which you got the other tasks

**Comment by TedLivist** [comment]
@williamscch they are there on the template from which you copied the other tasks

**Comment by BertrandConxy** [comment]
Hi team, 

Great work on making the changes requested by a previous reviewer 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 💪 
- kanban is set well

 ## Required Changes ♻️

- [x] Please assigned these **newly added cards to either one of you or both of you as they are group tasks**. What is essential is **that each of all cards should have an assignee (i.e: someone who is responsible to work on it)**

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by KDlamini** [comment]
### Hi team @williamscch, @amklass11 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes. 🎊 🥳 
Your Kanban task is complete!
Congratulations!!!

# Status: Approved ✔️ 
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments here if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
